# -*- rpm-spec -*-
BuildRoot:      %_topdir/suex-0.2.2-linux-amd64
Summary:        execute commands as another user
Name:           suex
Version:        0.2.2
Release:        1
License:        unknown
Group:          unknown
Vendor:         odedlaz

Source: suex-0.2.2.tar.gz




%define debug_package %{nil}

%define _rpmdir %_topdir/RPMS
%define _srcrpmdir %_topdir/SRPMS
%define _rpmfilename suex-0.2.2-linux-amd64.rpm
%define _unpackaged_files_terminate_build 0




%description
DESCRIPTION
===========

This is an installer created using CPack (https://cmake.org). No additional installation instructions provided.



# This is a shortcutted spec file generated by CMake RPM generator
# we skip _install step because CPack does that for us.
# We do only save CPack installed tree in _prepr
# and then restore it in build.
%prep
%setup -c


%build
mkdir cpack_rpm_build_dir
cd cpack_rpm_build_dir
cmake  -DCPACK_PACKAGING_INSTALL_PREFIX=/ ../suex-0.2.2-linux-amd64
make %{?_smp_mflags}

#p build

%install

cd cpack_rpm_build_dir
cpack -G RPM
mv *.rpm %_rpmdir

%clean

%changelog
* Sun Jul 4 2010 Eric Noulard <eric.noulard@gmail.com> - 0.2.2-1
  Generated by CPack RPM (no Changelog file were provided)
